/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ReceiveRouteImport } from './routes/receive'
import { Route as SendRouteImport } from './routes/send'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TroubleshootingRouteImport } from './routes/troubleshooting'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiveRoute = ReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => rootRouteImport,
} as any)
const SendRoute = SendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TroubleshootingRoute = TroubleshootingRouteImport.update({
  id: '/troubleshooting',
  path: '/troubleshooting',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/devices': typeof DevicesRoute
  '/history': typeof HistoryRoute
  '/receive': typeof ReceiveRoute
  '/send': typeof SendRoute
  '/settings': typeof SettingsRoute
  '/troubleshooting': typeof TroubleshootingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/devices': typeof DevicesRoute
  '/history': typeof HistoryRoute
  '/receive': typeof ReceiveRoute
  '/send': typeof SendRoute
  '/settings': typeof SettingsRoute
  '/troubleshooting': typeof TroubleshootingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/devices': typeof DevicesRoute
  '/history': typeof HistoryRoute
  '/receive': typeof ReceiveRoute
  '/send': typeof SendRoute
  '/settings': typeof SettingsRoute
  '/troubleshooting': typeof TroubleshootingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/devices'
    | '/history'
    | '/receive'
    | '/send'
    | '/settings'
    | '/troubleshooting'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/devices'
    | '/history'
    | '/receive'
    | '/send'
    | '/settings'
    | '/troubleshooting'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/devices'
    | '/history'
    | '/receive'
    | '/send'
    | '/settings'
    | '/troubleshooting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DevicesRoute: typeof DevicesRoute
  HistoryRoute: typeof HistoryRoute
  ReceiveRoute: typeof ReceiveRoute
  SendRoute: typeof SendRoute
  SettingsRoute: typeof SettingsRoute
  TroubleshootingRoute: typeof TroubleshootingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receive': {
      id: '/receive'
      path: '/receive'
      fullPath: '/receive'
      preLoaderRoute: typeof ReceiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/troubleshooting': {
      id: '/troubleshooting'
      path: '/troubleshooting'
      fullPath: '/troubleshooting'
      preLoaderRoute: typeof TroubleshootingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DevicesRoute: DevicesRoute,
  HistoryRoute: HistoryRoute,
  ReceiveRoute: ReceiveRoute,
  SendRoute: SendRoute,
  SettingsRoute: SettingsRoute,
  TroubleshootingRoute: TroubleshootingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
